"""

Revision ID: 0008_email_cols
Revises: 0007_naive_expiry_oauth
Create Date: 2025-03-13 12:59:17.880229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008_email_cols'
down_revision: Union[str, None] = '0007_naive_expiry_oauth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('first_history_id', sa.Integer(), nullable=True))
    op.add_column('email_messages', sa.Column('history_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('email_messages', sa.Column('label_ids', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'label_ids')
    op.drop_column('email_messages', 'history_ids')
    op.drop_column('email_messages', 'first_history_id')
    # ### end Alembic commands ###
