"""

Revision ID: 0009_email_nullable_to_address
Revises: 0008_email_cols
Create Date: 2025-03-13 20:38:41.497391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0009_email_nullable_to_address'
down_revision: Union[str, None] = '0008_email_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'to_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'to_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
