"""

Revision ID: 0013_push
Revises: 0012_add_event_timestamp
Create Date: 2025-05-03 11:22:50.867157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013_push'
down_revision: Union[str, None] = '0012_add_event_timestamp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_push_tokens_token'))
    )
    op.create_index(op.f('ix_push_tokens_email'), 'push_tokens', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_tokens_email'), table_name='push_tokens')
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
