"""
Pydantic models for Docuform template schemas.

These models define the structure for:
- Field schemas (individual fillable fields in a template)
- Template schemas (collection of fields with metadata)
- Field source tracking (client/attorney/ai)
"""
from datetime import datetime, timezone
from enum import Enum
from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    """Get current UTC time as timezone-aware datetime."""
    return datetime.now(timezone.utc)


class FieldSource(str, Enum):
    """Who provides the value for this field."""
    CLIENT = "client"       # Collected from client intake form
    ATTORNEY = "attorney"   # Entered by attorney during review
    AI = "ai"               # Generated by AI based on context


class FieldType(str, Enum):
    """Input type for form rendering."""
    TEXT = "text"           # Short text input
    TEXTAREA = "textarea"   # Long text (paragraphs)
    DATE = "date"           # Date picker
    CURRENCY = "currency"   # Money amount with formatting
    EMAIL = "email"         # Email with validation
    PHONE = "phone"         # Phone number
    ADDRESS = "address"     # Multi-field address
    SELECT = "select"       # Dropdown with options
    NUMBER = "number"       # Numeric input


class FieldSchema(BaseModel):
    """Schema for a single template field."""
    tag: str = Field(..., description="Content control tag (e.g., 'declarant.name')")
    alias: str = Field(default="", description="Human-readable alias from Word")
    display_name: str = Field(default="", description="Display label for forms")
    source: FieldSource = Field(default=FieldSource.CLIENT, description="Who provides this value")
    field_type: FieldType = Field(default=FieldType.TEXT, description="Input type for form rendering")
    current_value: str = Field(default="", description="Current/default value in template")

    # Optional grouping and ordering
    group: str | None = Field(default=None, description="Logical grouping for form layout")
    order: int = Field(default=0, description="Display order within group")
    required: bool = Field(default=True, description="Is this field required?")

    # Optional validation
    min_length: int | None = Field(default=None)
    max_length: int | None = Field(default=None)
    pattern: str | None = Field(default=None, description="Regex validation pattern")

    # For SELECT fields
    options: list[str] | None = Field(default=None)

    # For AI-sourced fields
    ai_prompt: str | None = Field(default=None, description="Prompt template for AI generation")
    ai_context_fields: list[str] | None = Field(default=None, description="Other fields used as context")


class TemplateSchema(BaseModel):
    """Complete schema for a document template."""
    template_filename: str = Field(..., description="Associated template filename")
    version: str = Field(default="1.0", description="Schema version")
    fields: list[FieldSchema] = Field(default_factory=list)

    # Metadata
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)
    created_by: str | None = Field(default=None, description="User who created/last updated")


class FieldSourceUpdate(BaseModel):
    """Request to update a single field's source."""
    tag: str
    source: FieldSource


class BulkFieldSourceUpdate(BaseModel):
    """Request to update multiple fields' sources at once."""
    updates: list[FieldSourceUpdate]
