"""

Revision ID: 0010_email_allow_null_subject
Revises: 0009_email_nullable_to_address
Create Date: 2025-03-13 21:21:24.873183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010_email_allow_null_subject'
down_revision: Union[str, None] = '0009_email_nullable_to_address'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_messages', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
