"""

Revision ID: 0011_open_phone_events
Revises: 0010_email_allow_null_subject
Create Date: 2025-03-29 11:52:50.027653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011_open_phone_events'
down_revision: Union[str, None] = '0010_email_allow_null_subject'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
