"""

Revision ID: 0011_open_phone_events
Revises: 0010_email_allow_null_subject
Create Date: 2025-03-29 17:40:17.260136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011_open_phone_events'
down_revision: Union[str, None] = '0010_email_allow_null_subject'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_phone_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('phone_number_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_open_phone_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_open_phone_events_event_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_phone_events')
    # ### end Alembic commands ###
