"""

Revision ID: 0018_contactcols
Revises: 0017_first_last_name
Create Date: 2025-05-13 20:39:58.486483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0018_contactcols'
down_revision: Union[str, None] = '0017_first_last_name'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('company', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('role', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('openphone_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'openphone_json')
    op.drop_column('contacts', 'role')
    op.drop_column('contacts', 'company')
    # ### end Alembic commands ###
