"""

Revision ID: 0020_add_pending_email_approvals_table
Revises: 0019_nullable_slug
Create Date: 2025-12-08 15:16:18.890060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0020_pending_approvals'
down_revision: Union[str, None] = '0019_nullable_slug'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_email_approvals',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('tool_call_id', sa.String(length=255), nullable=False),
    sa.Column('message_history', sa.Text(), nullable=False),
    sa.Column('email_to', sa.String(length=255), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('pk_pending_email_approvals'))
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('pending_email_approvals')
    # ### end Alembic commands ###
