"""

Revision ID: 0021_add_user_email
Revises: 0020_agent_conversations
Create Date: 2025-12-23 23:31:23.300304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0021_add_user_email'
down_revision: Union[str, None] = '0020_agent_conversations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_conversations', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_conversations', 'user_email')
    # ### end Alembic commands ###
