"""

Revision ID: 0023_index_optimize
Revises: 0022_rn_user_id_to_clerk_user_id
Create Date: 2025-12-28 21:44:50.455493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0023_index_optimize'
down_revision: Union[str, None] = '0022_rn_user_id_to_clerk_user_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agent_conv_user_agent_updated', 'agent_conversations', ['clerk_user_id', 'agent_name', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_conv_user_agent_updated', table_name='agent_conversations')
    # ### end Alembic commands ###
